import { Fragment } from "react";

function FirstChallenge({refo}){
    return(
      <Fragment>
        <div className="board-1" ref={refo} style={{"letterSpacing": '1em'}}>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
      </div>
      </Fragment>
    )
}

export default FirstChallenge;

//todo challenger o der