import React, {  Fragment } from "react";

function SecondChallange({refo}) {
  return (
    <Fragment>
      <div className="board-2" ref={refo}>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[140deg] inline-block right-3 top-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[48deg] inline-block top-2 right-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%)"}}>🌕</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[330deg] inline-block left-1 bottom-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span style={{"filter":"grayscale(100%) brightness(30%) sepia(100%) hue-rotate(-180deg) saturate(700%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(70%) sepia(50%) hue-rotate(-100deg) saturate(500%) contrast(1)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[330deg] inline-block left-1 bottom-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[140deg] inline-block right-3 top-1 relative">
              ☄️
            </span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span style={{filter: "grayscale(100%)"}}>🌕</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[230deg] inline-block right-3 bottom-2 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(30%) sepia(100%) hue-rotate(-180deg) saturate(700%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(40%) sepia(100%) hue-rotate(-50deg) saturate(600%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(70%) sepia(50%) hue-rotate(-100deg) saturate(500%) contrast(1)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%)"}}>🌕</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(30%) sepia(100%) hue-rotate(-180deg) saturate(700%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(70%) sepia(50%) hue-rotate(-100deg) saturate(500%) contrast(1)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(40%) sepia(100%) hue-rotate(-50deg) saturate(600%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[48deg] inline-block top-2 right-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[48deg] inline-block top-2 right-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(70%) sepia(50%) hue-rotate(-100deg) saturate(500%) contrast(1)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(30%) sepia(100%) hue-rotate(-180deg) saturate(700%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[330deg] inline-block left-1 bottom-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[230deg] inline-block right-3 bottom-2 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[140deg] inline-block right-3 top-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%)"}}>🌕</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(30%) sepia(100%) hue-rotate(-180deg) saturate(700%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[330deg] inline-block left-1 bottom-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%)"}}>🌕</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[140deg] inline-block right-3 top-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[230deg] inline-block right-3 bottom-2 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(30%) sepia(100%) hue-rotate(-180deg) saturate(700%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(30%) sepia(100%) hue-rotate(-180deg) saturate(700%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(70%) sepia(50%) hue-rotate(-100deg) saturate(500%) contrast(1)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[48deg] inline-block top-2 right-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(70%) sepia(50%) hue-rotate(-100deg) saturate(500%) contrast(1)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(40%) sepia(100%) hue-rotate(-50deg) saturate(600%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%)"}}>🌕</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span className="rotate-[140deg] inline-block right-3 top-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(40%) sepia(100%) hue-rotate(-50deg) saturate(600%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%)"}}>🌕</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(70%) sepia(50%) hue-rotate(-100deg) saturate(500%) contrast(1)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(40%) sepia(100%) hue-rotate(-50deg) saturate(600%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(30%) sepia(100%) hue-rotate(-180deg) saturate(700%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[330deg] inline-block left-1 bottom-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span style={{"filter": "grayscale(100%) brightness(40%) sepia(100%) hue-rotate(-50deg) saturate(600%) contrast(0.8)"}}>
              🌕
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[230deg] inline-block right-3 bottom-2 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[48deg] inline-block top-2 right-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🪐</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[230deg] inline-block right-3 bottom-2 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[230deg] inline-block right-3 bottom-2 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[48deg] inline-block top-2 right-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[330deg] inline-block left-1 bottom-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[140deg] inline-block right-3 top-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span className="rotate-[330deg] inline-block left-1 bottom-1 relative">
              ☄️
            </span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
        <div className="row">
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
          <span>
            <span>🌌</span>
          </span>
        </div>
      </div>
    </Fragment>
  );
}

export default SecondChallange;
